services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=monitordb'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  atm-monitor-server:
    container_name: 'atm-monitor-server'
    build:
      context: ./atmmonitorserver
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=password'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitordb'
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  atm-monitor-client:
    container_name: 'atm-monitor-client'
    build:
      context: ./atmmonitorclient
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - atm-monitor-server

volumes:
  postgres_data:
